# For adding a new service, define the following
# uri
# path
# headers
# client_id - Dev Portal token from A&A
# auth_token - Dev Portal token from A&A
# body
# output - info returned from the service after creation

uri: "https://apps.bcservices.dev"
path: "/users"
headers:
  client_id: #{}
  auth_token: #{}
  content-type: "application/json"
body:
  email: #{email}
  scopes: ["store_create_user", "store_edit_user", "store_delete_user"]
  is_owner: false,
  store_id: 12345
output:
  - id
  - email
